// <auto-generated />
using System;
using MMLinkedInAttempt57.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MMLinkedInAttempt57.Migrations
{
    [DbContext(typeof(MMLinkedInAttempt57Context))]
    partial class MMLinkedInAttempt57ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MMLinkedInAttempt57.Models.Guess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("playerGuess")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guesses");
                });

            modelBuilder.Entity("MMLinkedInAttempt57.Models.GuessTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FKGuessId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeOfGuess")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FKGuessId");

                    b.ToTable("GuessTimes");
                });

            modelBuilder.Entity("MMLinkedInAttempt57.Models.GuessTime", b =>
                {
                    b.HasOne("MMLinkedInAttempt57.Models.Guess", "Guess")
                        .WithMany("GuessTimes")
                        .HasForeignKey("FKGuessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guess");
                });

            modelBuilder.Entity("MMLinkedInAttempt57.Models.Guess", b =>
                {
                    b.Navigation("GuessTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
